'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class booking
    
    '''<summary>
    '''loginuser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loginuser As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''d_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents d_name As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''d_fee control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents d_fee As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''d_time control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents d_time As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''d_address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents d_address As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''d_phone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents d_phone As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''p_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p_name As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''p_contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p_contact As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''p_age control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p_age As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''p_problem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents p_problem As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''confirm_bookingxx control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents confirm_bookingxx As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''go_back control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents go_back As Global.System.Web.UI.WebControls.Button
End Class
