'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class doctor_home
    
    '''<summary>
    '''logindoctor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents logindoctor As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''doctor_image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents doctor_image As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''go control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents go As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''close_records control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents close_records As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''book_requests control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents book_requests As Global.System.Web.UI.WebControls.DataGrid
    
    '''<summary>
    '''c_book_see control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents c_book_see As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''c_book_close control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents c_book_close As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''c_book_div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents c_book_div As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''c_book_gd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents c_book_gd As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''feed1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents feed1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''feed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents feed As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''submit_feed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents submit_feed As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''feed_success control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents feed_success As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''see_details control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents see_details As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hide_details control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hide_details As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''firstone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents firstone As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''secondone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents secondone As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''e_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents e_name As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''e_age control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents e_age As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''e_contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents e_contact As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''e_email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents e_email As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''e_address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents e_address As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''e_gender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents e_gender As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''profile_image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents profile_image As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''imgupload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgupload As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''userimagevalidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents userimagevalidator As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''update_img control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents update_img As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''history_see control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents history_see As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''history_close control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents history_close As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''history_div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents history_div As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''history_book control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents history_book As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''oldpwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents oldpwd As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''newpwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newpwd As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rpwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpwd As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''logyes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents logyes As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''logno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents logno As Global.System.Web.UI.WebControls.Button
End Class
