'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class patient_home
    
    '''<summary>
    '''loginuser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loginuser As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''user_image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents user_image As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''choose_category control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents choose_category As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''choose_location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents choose_location As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''proceed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents proceed As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''close control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents close As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''gd1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gd1 As Global.System.Web.UI.WebControls.DataGrid
    
    '''<summary>
    '''track_id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents track_id As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''track_button control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents track_button As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''t_close control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_close As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''track_data control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents track_data As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''t_status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_status As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''t_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_name As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''t_age control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_age As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''t_contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_contact As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''t_problem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_problem As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''t_dname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_dname As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''t_address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_address As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''t_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_date As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''t_time control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_time As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''t_cancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_cancel As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''not_found control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents not_found As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''cancelledbooking control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cancelledbooking As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''history_see control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents history_see As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''history_close control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents history_close As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''history_div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents history_div As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''history_book control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents history_book As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''fedfocus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fedfocus As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''feed1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents feed1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''feed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents feed As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''submit_feed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents submit_feed As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''feed_success control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents feed_success As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''oldpwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents oldpwd As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''newpwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents newpwd As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rpwd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpwd As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''firstone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents firstone As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''see_details control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents see_details As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''hide_details control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hide_details As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''thirdone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents thirdone As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''secondone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents secondone As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''e_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents e_name As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''e_age control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents e_age As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''e_contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents e_contact As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''e_email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents e_email As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''e_address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents e_address As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''e_gender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents e_gender As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''profile_image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents profile_image As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''imgupload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgupload As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''userimagevalidator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents userimagevalidator As Global.System.Web.UI.WebControls.CustomValidator
    
    '''<summary>
    '''invalid_image control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents invalid_image As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''update_img control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents update_img As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''logyes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents logyes As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''logno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents logno As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''manu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents manu As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
