'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class showbookings
    
    '''<summary>
    '''search_patientname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents search_patientname As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''search_status control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents search_status As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''filter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filter As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''clearfilter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clearfilter As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''search_bookingid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents search_bookingid As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''filter2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents filter2 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''clearfilter2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents clearfilter2 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''showbookings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents showbookings As Global.System.Web.UI.WebControls.DataGrid
End Class
